# TODO: Choose a java JRE
FROM eclipse-temurin:21-jre-alpine

# TODO:  Add the compiled java (aka bytecode, aka .class)
COPY ./Main.class .

# TODO: Run the Java with: “java Main” command.
CMD ["java", "Main"]