#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/database
- name: Launch database
  community.docker.docker_container:
    name: database
    image: ilovedockingandfrotting/tp-devops-database
    state: started
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env:
      POSTGRES_DB: "{{ DB_NAME }}"
      POSTGRES_USER: "{{ DB_NAME }}"
      POSTGRES_PASSWORD: "{{ DB_PASSWORD }}"
