#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/database
- name: Launch database
  community.docker.docker_container:
    name: database
    image: ilovedockingandfrotting/tp-devops-database:latest
    restart_policy: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - name: app-network
    env:
      POSTGRES_DB: "{{ DB_NAME }}"
      POSTGRES_USER: "{{ DB_USERNAME }}"
      POSTGRES_PASSWORD: "{{ DB_PASSWORD }}"
