#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/database
- name: Copy .env file to server
  copy:
    src: .env
    dest: /home/admin/.env
    mode: '0600'

- name: Create Docker volume for PostgreSQL
  community.docker.docker_volume:
    name: postgres-data
    state: present

- name: Launch database
  community.docker.docker_container:
    name: database
    image: ilovedockingandfrotting/tp-devops-database
    state: started
    restart_policy: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - name: app-network
    env:
      POSTGRES_DB: "{{ DB_NAME }}"
      POSTGRES_USER: "{{ DB_USERNAME }}"
      POSTGRES_PASSWORD: "{{ DB_PASSWORD }}"
